# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_auto_20170127_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='category',
            field=models.CharField(choices=[('ko', 'korean'), ('jp', 'japanese'), ('cn', 'chinese')], default='ko', max_length=2),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='메뉴 이미지'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=50, verbose_name='메뉴 이름'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.PositiveIntegerField(verbose_name='가격'),
        ),
    ]
